workflows:
  android-app:
    name: Build Android APK

    environment:
      groups:
        - default

    scripts:
      - name: Clean project
        script: ./gradlew clean

      - name: Build release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
